version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true
branches:
  only:
  - master
skip_tags: true
build_script:
- ps: '& ".\build.ps1"'
test: off
artifacts:
- path: '\whats-new*.nupkg'
  name: whats-new
deploy:
- provider: Environment
  name: myget:chocolatey
  on:
    branch: master
